### ISSUE TITLE
Must be recompiled with latest libtesla

### ISSUE THREAD

**Issue by fennectech** [HookedBehemoth/screen-nx#11]
https://github.com/Atmosphere-NX/Atmosphere/issues/965

WerWolvToday at 10:48 AM
I pushed it to Tesla already
rip
FennecTECHToday at 10:48 AM
Mk
I’m free to test
WerWolvToday at 10:49 AM
There isn't much to test lol
Devs have to rebuild their overlays too

**Comment by HookedBehemoth** [comment]
Wrong repo but ok

**Comment by HookedBehemoth** [comment]
https://github.com/HookedBehemoth/ShareNX-Overlay/releases/latest
