### ISSUE TITLE
May I please have a appropriate image to the bottom left side of my screen? 

### ISSUE THREAD

**Issue by Aliasim800** [HookedBehemoth/screen-nx#12]
Ok so when I look at this picture which is shown in the repo:
![20200708_232754](https://user-images.githubusercontent.com/64366457/86976738-05be9f80-c173-11ea-9572-bd686bdd9d2a.jpg)
It's really nice and I actually like it.
But when I get the app and open it up I am greeted by this:
![20200708_232851](https://user-images.githubusercontent.com/64366457/86976766-1f5fe700-c173-11ea-93a2-d86484c40ec0.jpg)
Which to be honest I am not fond of at all.
What I'm happy with is if you upload the first image I showed which i found on the repo (by replying to this issue and just attaching the image).
You can keep the other inappropriate picture as is if you like, what the big deal is for me is that I just want a nice picture on the bottom left of my screen, I know I can remove it completely but I would prefer it if you could please just send me the one I showed you firstly.
Thank you!

**Comment by hax4dazy** [comment]
Compile the program yourself :shrek:

**Comment by Aliasim800** [comment]
I want the image. When I can ask for it and get it simply without a problem why not? Also the image in the repo is completely different to the one I am greeted with when I actually open the app, I call that fake advertising

**Comment by HookedBehemoth** [comment]
There was no release since the image was reverted.

Since everything is being rewritten you'll have to wait a little bit longer.

**Comment by Aliasim800** [comment]
Ok then, I thought I could just get the image.

**Comment by Aliasim800** [comment]
Actually! I downloaded the source code of the first initial release and found the image I wanted in the sources folder. I'm happy and thank you for your time!
