### ISSUE TITLE
Files in wrong order and slow scrolling

### ISSUE THREAD

**Issue by Brawl345** [HookedBehemoth/screen-nx#2]
Thanks for the app, very useful since my Switch is banned!
For me the files are in the wrong order. A picture from 31st August is listed first and from 1st september last. The order is kinda weird: the files decrease first and the newest picture is somewhere in the middle (from 23rd september).

Also, scrolling the first five pictures is fast, but when scrolling further down it gets slow. Maybe you can also add scrolling pagewise via R and faster scrolling with holding down the buttons? Thanks!

**Comment by HookedBehemoth** [comment]
Slow scrolling is an issue with how images are loaded atm. I don't create thumbnails so every time a new image is shown it gets loaded from SD again.

**Comment by Brawl345** [comment]
OK, but at least it's now sorted correctly so scrolling is not needed for me :P Thanks!

**Comment by Huntereb** [comment]
Fixed by https://github.com/HookedBehemoth/screen-nx/commit/d8b918eaf923699649e8003a2e8f956092dd78b6 !
